Dev 1.1.0 data source (#1271)
* Repair the problem in rest controllers; Add JsonErrorException; Enhance the strategy in DataSourceParameterValidator

* Enhance the loading method in MetaClassLoaderManager; Add MetaMethodInvokeException

* Change the assembly files in linkis-metadata-manager/service

* Adjust the directory name and the startup/stop script content

* Complete the linkis-datasource-client module

* Add the require annotation @RequestBody

diff --git a/assembly-combined-package/assembly-combined/sbin/ext/linkis-ps-metadatamanager b/assembly-combined-package/assembly-combined/sbin/ext/linkis-ps-metadatamanager
--- a/assembly-combined-package/assembly-combined/sbin/ext/linkis-ps-metadatamanager
+++ b/assembly-combined-package/assembly-combined/sbin/ext/linkis-ps-metadatamanager
@@ -18,16 +18,65 @@
 # Modified for Linkis 1.0.0
 
 
-export SERVER_SUFFIX="linkis-public-enhancements/linkis-ps-metadatamanager"
+source $LINKIS_CONF_DIR/linkis-env.sh
 
-#export DEBUG_PORT=
+SERVER_SUFFIX="linkis-public-enhancements/linkis-ps-metadatamanager"
+
 
 export SERVER_CLASS=org.apache.linkis.metadatamanager.server.LinkisMetadataManagerApplication
 
-export COMMON_START_BIN=$LINKIS_HOME/sbin/ext/linkis-common-start
-if [[ ! -f "${COMMON_START_BIN}" ]]; then
-    echo "The $COMMON_START_BIN  does not exist!"
+if [ "$LINKIS_LOG_DIR" = "" ]; then
+  export LINKIS_LOG_DIR="$LINKIS_HOME/logs"
+fi
+if [ ! -w "$LINKIS_LOG_DIR" ] ; then
+  sudo mkdir -p $LINKIS_LOG_DIR; sudo chown -R hadoop:hadoop $LINKIS_LOG_DIR
+fi
+
+if test -z "$SERVER_HEAP_SIZE"
+then
+  export SERVER_HEAP_SIZE="512M"
+fi
+
+if [ "$DEBUG_PORT" ];
+then
+   export DEBUG_CMD="-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=$DEBUG_PORT"
+fi
+
+if test -z "$SERVER_JAVA_OPTS"
+then
+  export SERVER_JAVA_OPTS=" -DserviceName=$SERVER_NAME -Xmx$SERVER_HEAP_SIZE -XX:+UseG1GC -Xloggc:$LINKIS_LOG_DIR/${SERVER_NAME}-gc.log $DEBUG_CMD "
+fi
+
+## conf dir
+export SERVER_CONF_PATH=$LINKIS_CONF_DIR
+
+## commons lib
+export LINKIS_COMMONS_LIB=$LINKIS_HOME/$LINKIS_PUBLIC_MODULE
+if [ ! -r "$LINKIS_COMMONS_LIB" ] ; then
+    echo "linkis commons lib not exists $LINKIS_COMMONS_LIB"
+    exit 1
+fi
+
+## server lib
+export SERVER_LIB=$LINKIS_HOME/lib/$SERVER_SUFFIX
+if [ ! -r "$SERVER_LIB" ] ; then
+    echo "server lib not exists $SERVER_LIB"
+    exit 1
+fi
+# set the wds.linkis.server.mdm.service.lib.dir to ${SERVER_LIB}/service
+SERVER_JAVA_OPTS=" -Dwds.linkis.server.mdm.service.lib.dir=${SERVER_LIB}/service"${SERVER_JAVA_OPTS}
+
+## set class path
+export SERVER_CLASS_PATH=$SERVER_CONF_PATH:$LINKIS_COMMONS_LIB/*:$SERVER_LIB/*
+
+nohup java $SERVER_JAVA_OPTS -cp $SERVER_CLASS_PATH $SERVER_CLASS $SPRING_ARGS 2>&1 > $LINKIS_LOG_DIR/${SERVER_NAME}.out &
+
+pid=$!
+sleep 2
+if [[ -z "${pid}" ]]; then
+    echo "server $SERVER_NAME start failed!"
     exit 1
 else
-    sh $COMMON_START_BIN
+    echo "server $SERVER_NAME start succeeded!"
+    echo $pid > $SERVER_PID
 fi
