Revert "fix: fix conflict when merge dev-1.3.0 to dev-1.3.1"

diff --git a/linkis-dist/package/sbin/ext/linkis-mg-eureka b/linkis-dist/package/sbin/ext/linkis-mg-eureka
--- a/linkis-dist/package/sbin/ext/linkis-mg-eureka
+++ b/linkis-dist/package/sbin/ext/linkis-mg-eureka
@@ -90,31 +90,16 @@ else
 fi
 
 SPRING_ARGS="$SPRING_ARGS --spring.profiles.active=eureka"
-
 echo  "=====Java Start Command====="
+echo  "nohup java $SERVER_JAVA_OPTS -cp $SERVER_CLASS_PATH $SERVER_CLASS $SPRING_ARGS 2>&1 > $LINKIS_LOG_DIR/${SERVER_NAME}.out &"
+nohup java $SERVER_JAVA_OPTS -cp $SERVER_CLASS_PATH $SERVER_CLASS $SPRING_ARGS 2>&1 > $LINKIS_LOG_DIR/${SERVER_NAME}.out &
 
-if [ "X${RUN_IN_FOREGROUND}" == "Xtrue" ]; then
-
-  echo  "java $SERVER_JAVA_OPTS -cp $SERVER_CLASS_PATH $SERVER_CLASS $SPRING_ARGS 2>&1"
-  java $SERVER_JAVA_OPTS -cp $SERVER_CLASS_PATH $SERVER_CLASS $SPRING_ARGS 2>&1
-
+pid=$!
+sleep 2
+if [[ -z "${pid}" ]]; then
+    echo "server $SERVER_NAME start failed!"
+    exit 1
 else
-
-  echo  "nohup java $SERVER_JAVA_OPTS -cp $SERVER_CLASS_PATH $SERVER_CLASS $SPRING_ARGS 2>&1 > $LINKIS_LOG_DIR/${SERVER_NAME}.out &"
-  nohup java $SERVER_JAVA_OPTS -cp $SERVER_CLASS_PATH $SERVER_CLASS $SPRING_ARGS 2>&1 > $LINKIS_LOG_DIR/${SERVER_NAME}.out &
-
-  pid=$!
-  sleep 2
-  if [[ -z "${pid}" ]]; then
-      echo "server $SERVER_NAME start failed!"
-      exit 1
-  else
-      echo "server $SERVER_NAME start succeeded!"
-      echo $pid > $SERVER_PID
-
-      if [ "X${RUN_IN_FOREGROUND}" == "Xtrue" ]; then
-        wait $pid || exit -1
-      fi
-  fi
-
+    echo "server $SERVER_NAME start succeeded!"
+    echo $pid > $SERVER_PID
 fi
