[ISSUE-3227] Optimize git action  (#3228)
* optimize git action

diff --git a/.github/workflows/check-license.yml b/.github/workflows/check-license.yml
--- a/.github/workflows/check-license.yml
+++ b/.github/workflows/check-license.yml
@@ -15,21 +15,31 @@
 # specific language governing permissions and limitations
 # under the License.
 
-
-name: Dead Link Check
+name: License Check
 
 on: [push, pull_request]
 
 jobs:
-  dead-links-check:
+  apache-rat-check:
     runs-on: ubuntu-latest
-    timeout-minutes: 30
-    if: (github.repository == 'apache/incubator-linkis')
     steps:
-      - uses: actions/checkout@v3
-      - uses: gaurav-nelson/github-action-markdown-link-check@v1
+      - name: Checkout source
+        uses: actions/checkout@v2
+      - name: Set up JDK 8
+        uses: actions/setup-java@v2
         with:
-          use-quiet-mode: 'no'
-          use-verbose-mode: 'yes'
-          folder-path: '../'
-          config-file: '.github/workflows/dlc.json'
+          java-version: '8'
+          distribution: 'adopt'
+      - name: mvn -N install
+        run:
+          mvn -N install
+      - name: License check with Maven
+        run: |
+          rat_file=`mvn apache-rat:check  | { grep -oe "\\S\\+/rat.txt" || true; }`
+          echo "rat_file=$rat_file"
+          if [[ -n "$rat_file" ]];then  echo "check error!" && cat $rat_file && exit 123;else echo "check success!" ;fi
+      - name: Upload the report
+        uses: actions/upload-artifact@v2
+        with:
+          name: license-check-report
+          path: "**/target/rat.txt"
